### PR TITLE
Fix handling of incoming packets

### LINKED ISSUE #19: Walk-through unsafe handling of incoming packets
Currently packets in the walkthrough are handled in an unsafe way. The following logic is currently implemented:
- receive a new state from other party
- sign the state
- respond to the state
- check if the state was valid
Which means currently invalid states are signed. This is a major security flaw.

```
//VPC State version 2 - by bob
	//Read, Sign and send back the vpc state with accept
	vpcStateSigned02, err := newConnToBob.NewVPCStateRead()
	if err != nil {
		_, _ = printer.Printf("\nVpc state read error - %v\n", err)
		return
	}
	aliceID.SetCredentials(testKeystore, alicePassword)
	if err = vpcStateSigned02.AddSign(aliceID, channel.Sender); err != nil {
		_, _ = printer.Printf("\nSigning vpc state error - %v\n", err)
		return
	}
	err = newConnToBob.NewVPCStateRespond(vpcStateSigned02, channel.MessageStatusAccept)
	if err != nil {
		_, _ = printer.Printf("\nVpc state respond error - %v\n", err)
		return
	}

	err = newConnToBob.SetCurrentVPCState(vpcStateSigned02)
	if err != nil {
		_, _ = printer.Printf("\nVpc state error - %v\n", err)
		return
	}
	_, _ = printer.Printf("\nVpc state - %+v\n", vpcStateSigned02)
```

This is because SetCurrentVPCState executes the checks on the state. These checks should be refactored into their own function. It should look like the following: 
```
//VPC State version 2 - by bob
	//Read, Sign and send back the vpc state with accept
	vpcStateSigned02, err := newConnToBob.NewVPCStateRead()
	if err != nil {
		_, _ = printer.Printf("\nVpc state read error - %v\n", err)
		return
	}
        if err := checkState(vpcStateSigned02); err != nil {
		_, _ = printer.Printf("\nVpc state invalid - %v\n", err)
		return
	}
	aliceID.SetCredentials(testKeystore, alicePassword)
	if err = vpcStateSigned02.AddSign(aliceID, channel.Sender); err != nil {
		_, _ = printer.Printf("\nSigning vpc state error - %v\n", err)
		return
	}
	err = newConnToBob.NewVPCStateRespond(vpcStateSigned02, channel.MessageStatusAccept)
	if err != nil {
		_, _ = printer.Printf("\nVpc state respond error - %v\n", err)
		return
	}

	err = newConnToBob.SetCurrentVPCState(vpcStateSigned02)
	if err != nil {
		_, _ = printer.Printf("\nVpc state error - %v\n", err)
		return
	}
	_, _ = printer.Printf("\nVpc state - %+v\n", vpcStateSigned02)
```

### PR DESCRIPTION
**Pull request by manoranjith**
- Added generic validation for received state and full state.
- Also fixed modification of input arguments in VerifySignatureEth
function. See identity/signature_ethereum.go.

Resolves #19

Signed-off-by: Manoranjith <ponraj.manoranjitha@in.bosch.com>

### CODE REVIEW

File: channel/manager_test.go [hunk 1]
```diff
@@ -1233,17 +1233,77 @@ func Test_Instance_MSCBaseState(t *testing.T) {
...
+				vpcState: VPCStateSigned{
+					VPCState: VPCState{
+						ID:              []byte("sample-id"),
+						Version:         big.NewInt(1),
+						BlockedSender:   big.NewInt(10),
+						BlockedReceiver: big.NewInt(20),
+					},
+				},
+			},
+		},
```
Comment (danielksan81) [inline channel/manager_test.go]: What is a possible scenario for this to be true?

File: channel/manager.go [hunk 2]
```diff
@@ -331,38 +331,79 @@ func (inst *Instance) MscBaseState() MSCBaseStateSigned {
...
+	return true, ""
+}
+
+// SetCurrentVPCState adds newState to vpc state list of the channel.
+// Validity of the state will not be checked, should be done prior to calling this function.
+func (inst *Instance) SetCurrentVPCState(newState VPCStateSigned) {
 	inst.vpcStatesList = append(inst.vpcStatesList, newState)
-	return nil
+	logger.Debug("New MSC base state set")
 }
```
Comment (danielksan81) [inline channel/manager.go]: Currently I'm not sure if it makes sense to be able to add states without any validation.
Does it make sense to call here `ValidateFullState`?

File: channel/manager_test.go (hunk 1 above)
Comment (manoranjith) [reply channel/manager_test.go]: This test case is to show that, whether the state is valid or not, it will be updated in the channel.

File: channel/manager.go (hunk 2 above)
Comment (manoranjith) [reply channel/manager.go]: As stated in documentation of this function, the state should be validated before updating to the Instance. 
Because, two types of validation needs to be done : 
1. Integrity of the state and signatures over it.
2. Correctness of the state according to the specific application.
(Second part of validation will vary depending upon the specific application)

First part of the validation can be done by calling ValidFullState and second part needs to be implemented by the application and called before calling SetCurrentVPCState  .

**Comment by danielksan81** [comment]
Title should be "Fix handling of incoming packets" as it is general behavior and not only targeting the walkthrough

File: channel/manager.go (hunk 2 above)
Comment (danielksan81) [reply channel/manager.go]: Point number 2 can only be done by the application or user, that's right.
Point number 1 is at least from my point of view mandatory, otherwise it does not make sense to add a state as valid. The other option is to distinguish between valid and intermediate, which is not treated as valid. Am I right that the `vpcStatesList` only holds valid states?

Comment (manoranjith) [reply channel/manager.go]: Yes, you are right that `vpcStateList` will hold only valid states. 

If the correctness of the state according to application logic will be validated before adding the signature of the user (part 2), then a state with two signatures can be implicitly considered correct with respect to the application logic.

And it will be sufficient to check only the integrity of signatures over it before adding it to `vpcStateList`.

I will make changes accordingly and update the pull request.

File: channel/manager_test.go (hunk 1 above)
Comment (danielksan81) [reply channel/manager_test.go]: new changes are reflecting that only valid states can be added
